name: Tag Service

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'How much to bump the version by'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      service:
        description: 'Which service to release'
        required: true
        type: choice
        options:
          - op-node
          - op-batcher
          - op-proposer
          - proxyd
          - indexer

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --tags origin
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install packaging
      - run: ops/scripts/tag-service.py ${{ github.event.inputs.bump }} ${{ github.event.inputs.service }}
        env:
          INPUT_GITHUB_TOKEN: ${{ github.token }}
